name: presentation
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  badges: ^3.0.2
  after_layout: ^1.2.0
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0
  go_router: ^6.2.0
  modal_bottom_sheet: ^3.0.0-pre
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  configurable_expansion_tile_null_safety: ^3.2.0
  flutter_bloc: ^8.1.2
  pin_code_fields: ^7.4.0
  equatable: ^2.0.5
  firebase_auth: ^4.4.0
  lottie: ^2.3.1
  intl: ^0.18.0
  flutter_html: 3.0.0-alpha.6
  flutter_html_table: 3.0.0-alpha.4
  flutter_html_svg: 3.0.0-alpha.4
  flutter_html_iframe: ^3.0.0-alpha.4
  timer_count_down: ^2.2.0
  font_awesome_flutter: ^10.4.0
  smooth_page_indicator: ^1.1.0
  collection: ^1.17.0
  cached_network_image: ^3.2.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.0
  go_router_builder: ^1.2.1

flutter_gen:
  null_safety: true # Optional (default: true)
  output: lib/generated/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true
  assets:
    outputs:
      enable: true
      package_parameter_enabled: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated/
  use_deferred_loading: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/raws/
    - assets/mock_data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Playfair
  #     fonts:
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-Regular.ttf
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-MediumItalic.ttf
  #         style: italic
  #         weight: 500
  #       - asset: assets/fonts/play_fair/PlayfairDisplay-BoldItalic.ttf
  #         style: italic
  #         weight: 700