name: presentation
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  flutter_form_builder: ^7.8.0
  badges: ^3.0.2
  after_layout: ^1.2.0
  flutter_svg: ^2.0.3
  auto_size_text: ^3.0.0
  go_router: ^6.2.0
  modal_bottom_sheet: ^3.0.0-pre
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  configurable_expansion_tile_null_safety: ^3.2.0
  flutter_bloc: ^8.1.2
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true