name: presentation
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  flutter_form_builder: ^7.8.0
  badges: ^3.0.2
  after_layout: ^1.2.0
  flutter_svg: ^2.0.3
  auto_size_text: ^3.0.0
  go_router: ^6.2.0
  modal_bottom_sheet: ^3.0.0-pre
  get_it: ^7.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true