name: core
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: data
  presentation:
    path: presentation

dev_dependencies:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Playfair
  #     fonts:
  #       - asset: fonts/play_fair/PlayfairDisplay-Regular.ttf
  #       - asset: fonts/play_fair/PlayfairDisplay-Bold.ttf
  #         weight: 700
  #       - asset: fonts/play_fair/PlayfairDisplay-Medium.ttf
  #         weight: 500
  #       - asset: fonts/play_fair/PlayfairDisplay-Italic.ttf
  #         style: italic
  #       - asset: fonts/play_fair/PlayfairDisplay-MediumItalic.ttf
  #         style: italic
  #         weight: 500
  #       - asset: fonts/play_fair/PlayfairDisplay-BoldItalic.ttf
  #         style: italic
  #         weight: 700
